### ISSUE TITLE
Feature Request  example with 3 servos for Arduino Nano

### ISSUE THREAD

**Issue by erguro1973** [fitzterra/ServoOsc#1]
Hello
First of all thanks for share this info, I haven´t got software programming skills, I tried to use basic example for managing 3 servos with no luck
It will be possible to add 2 servos more in pin 3 and 4 of Arduino?

Thanks in advance

Best regards

**Comment by fitzterra** [comment]
Hi @erguro1973 

To add more servos, you just need to set them up and then attach them to the pin required. Here is some basic example that might work (not tested):

```c++
#include <ServoOsc.h>

// Instantiate global instances without attaching yet
ServoOsc osc1(1000, 90, 0, 0, 0, 3, false);   // Pin 3
ServoOsc osc2(2000, 45, 0, 0, 0, 4, false);   // Pin 4
ServoOsc osc3(3000, 90, 20, 0, 0, 5, false);  // Pin 5

void setup() {
    // Attach osc1 to osc3
    osc1.attach();
    osc2.attach();
    osc3.attach();
}

void main() {
    osc1.update();
    osc2.update();
    osc3.update();
    delay(10);
}
```

Hope this helps.

**Comment by erguro1973** [comment]
Thank you so much for fast reply
